inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - bin/*
    - config
    - db/migrate/*.rb
    - db/schema.rb