tests:
  class: '::Forms::Test'
  name: 'Tests'
  permissions:
    - key: 'test_index'
      action: 'index'
      label: 'Access tests list'
    - key: 'test_create'
      action: 'create'
      label: 'Add new tests'
    - key: 'test_show'
      action: 'show'
      label: 'Show test'
    - key: 'test_edit'
      action: 'edit'
      label: 'Edit tests'
    - key: 'test_delete'
      action: 'delete'
      label: 'Delete tests'

responses:
  class: '::Forms::Response'
  name: 'Responses'
  permissions:
    - key: 'response_index'
      action: 'index'
      label: 'Access responses list'
    - key: 'response_show'
      action: 'show'
      label: 'Show response'
    - key: 'response_create'
      action: 'create'
      label: 'Create new responses'