forms:

  test:

    name: 'Tests'
    permissions:

      - action: 'view'
        label:  'View existing tests'

      - action: 'update'
        label:  'Update existing and create new tests'

      - action: 'delete'
        label:  'Delete existing tests'
        # conditions:
        #
        #   has_alerts:
        #     type: 'select'
        #     label: 'Has alerts'
        #     options:
        #       all: 'All'
        #       yes: 'Tests with alerts'

  response:

    name: 'Responses'
    permissions:

      - action: 'view'
        label:  'View test responses'

      - action: 'create'
        label:  'Create new responses / launch tests for candidates'

      - action: 'update'
        label:  'Assess test responses'

  mistake_type:

    name: 'Settings -> Mistake Types'
    permissions:

      - action: 'view'
        label:  'View mistake types'

      - action: 'update'
        label:  'Update existing and create new mistake types'

      - action: 'delete'
        label:  'Delete mistake types'

staff:

  user:

    name: 'Settings -> Users'
    permissions:

      - action: 'view'
        label:  'View users'

      - action: 'update'
        label:  'Update users'

  role:

    name: 'Settings -> Roles'
    permissions:

      - action: 'view'
        label:  'View roles'

      - action: 'update'
        label:  'Update and create roles'

      - action: 'delete'
        label:  'Delete roles'
